### ISSUE TITLE
Patents in relation to the standard

### ISSUE THREAD

**Issue by shawnmasters** [c2pa-org/public-draft#18]
How is the standard going to handle patents in relation to the standard and implementation?  Will it take an open standard like the [IETF](https://www.ietf.org/standards/ipr/)?

**Comment by jorydotcom** [comment]
Hi @shawnmasters, thank you for your question. The C2PA has adopted an open standard patent policy via W3C's Patent Mode (2004):

> **Licensing Commitment.**  For materials other than source code or datasets developed by the Working Group, each Working Group Participant agrees to make available any of its Essential Claims, as defined in the W3C Patent Policy (available at http://www.w3.org/Consortium/Patent-Policy-20040205), under the W3C RF licensing requirements Section 5 (http://www.w3.org/Consortium/Patent-Policy-20040205), in Approved Deliverables adopted by that Working Group as if that Approved Deliverable was a W3C Recommendation.  Source code developed by the Working Group is subject to the license set forth in the Working Group charter.  
> **For Exclusion**.  Prior to the adoption of a Draft Deliverable as an Approved Deliverable, a Working Group Participant may exclude Essential Claims from its licensing commitments under this agreement by providing written notice of that intent to the Working Group chair (“Exclusion Notice”).  The Exclusion Notice for issued patents and published applications must include the patent number(s) or title and application number(s), as the case may be, for each of the issued patent(s) or pending patent application(s) that the Working Group Participant wishes to exclude from the licensing commitment set forth in Section 1 of this patent policy.  If an issued patent or pending patent application that may contain Essential Claims is not set forth in the Exclusion Notice, those Essential Claims shall continue to be subject to the licensing commitments under this agreement.  The Exclusion Notice for unpublished patent applications must provide either: (i) the text of the filed application; or (ii) identification of the specific part(s) of the Draft Deliverable whose implementation makes the excluded claim an Essential Claim.  If (ii) is chosen, the effect of the exclusion will be limited to the identified part(s) of the Draft Deliverable. The Working Group Chair will publish Exclusion Notices

**Comment by c2pa-feedback** [comment]
And this issues also points out that we need to included that language in the spec as well!

**Comment by lrosenthol** [comment]
Linux Foundation legal has informed us that this information should not be in the draft documents but should appear in the final version.  I will leave this issue open until we merge it into the final version.

**Comment by shawnmasters** [comment]
Can you also leave a pointer in the draft to denote that the language is planned to be added into the final document?

**Comment by lrosenthol** [comment]
Yes, we can do that - good suggestion!

**Comment by lrosenthol** [comment]
This material has now been merged into the 1.0 specification we are working on!   I am going to leave this open till that is published...

**Comment by lrosenthol** [comment]
Published!

**Comment by ronalddas** [comment]
Hi, I had some doubts, Even if someone is not a part of the C2PA members ( https://c2pa.org/membership/) , can they still use their own implementation of the public draft for commercial use?

**Comment by lrosenthol** [comment]
@ronalddas Absolutely!   It is clearly spelled out at https://c2pa.org/specifications/specifications/1.0/specs/C2PA_Specification.html#_patent_policy
