### ISSUE TITLE
Provide some guidance on using DIDs as identifiers for assets

### ISSUE THREAD

**Issue by lrosenthol** [c2pa-org/public-draft#21]
From the W3C's Credential CG
>But DIDs are expressly designed to identify anything -- including the 'asset'. Why limit it to just an 'actor'. DIDs were not designed merely to apply to 'actors' like people and machines. They also refer to specific assets like your 'image, video, document'. But you're not taking advantage of this, apparently. 

>As I was getting at above: how will you handle, say, a small publisher or self-publisher of assets which they are identifying using a system of DIDs. What if the publisher, or author, and each of the assets they produce, are all identified as a linked system of DIDs, so that a user refers back to the DID Document from any asset. Can this somehow be integrated into the C2PA system?

Absolutely!  The Schema.org grammar for a CreativeWork – which is a component of the C2PA manifest – has a pre-defined field called (oddly enough) `identifier` which would be the logical spot for the asset’s DID to be recorded.   You can use additional CreativeWork fields to refer to other referenced/linked works if you wished.

In addition, the DID could serve as the `instanceID` for a claim or ingredient.

**Comment by hackerfactor** [comment]
Section 7.1 uses "DID" as a unique document identifier. This seems to redefine the definition as used by XMP.

In XMP, DID is the document identifier (identifies the parent source). IID is the instance identifier (identifies the current save/alteration).

**Comment by lrosenthol** [comment]
The change here would be in 6.2, Other Identifiers.    TWG agrees to add this.

**Comment by lrosenthol** [comment]
Such guidance is given in the second public draft of the document.
