### ISSUE TITLE
C2PA Public Draft (0.7) is Missing is a proper Problem Statement

### ISSUE THREAD

**Issue by yogeshbdeshpande** [c2pa-org/public-draft#22]
**Describe the issue**
C2PA Public Draft (0.7) is Missing is a proper Problem Statement.

It is highly desirable that C2PA specification writer needs to have a separate section of Problem Statement, which clearly describe in adequate detail, what exactly is the issue which C2PA is attempting to solve.

Otherwise, first time reader really has to read a ton to understand what problem C2PA is trying to solve ?

**Comment by lrosenthol** [comment]
Section 1, the Overview and Introduction seems to address this in quite a lot of detail.

Can you explain what you think is missing?  or what type of user(s) are not served by the provided material?

**Comment by lrosenthol** [comment]
TWG requests more input from the submitter...

**Comment by yogeshbdeshpande** [comment]
@lrosenthol I also read the specification:

Clearly Only first line states that:
With the digital transformation of information sharing, establishing the provenance of media has become critical. 
then we talk about what the specification does: Provenance techniques etc. etc.??

Clearly we lack a Problem Statement:

We should have a Problem Statement (however obvious it might sound) on something similar lines, I tried below:

**Problem Statement:**
With the extensive use of social media and open media platforms have given great freedom and flexibility to the common users. Now users can create content very easily, modify or manipulate it and post them on social media platforms with little or no effort.  However with the kind of freedom comes a natural side effect. Ill-intentioned or Malafied actors use the flexibility to their convenience by turning genuine videos into fake videos. << Add suitable description about deep fakes >>. << One live example about the problem  via recent example with a internet link, will help the cause >>

To address the above problem C2PA organization is formed. Now the para linking how this problem is addressed is well connected to the existing text in the C2PA specification.

**Comment by lrosenthol** [comment]
I understand now @yogeshbdeshpande - thanks!

What do you think about this material based on the introduction from original CAI Whitepaper.

>With the increasing velocity of digital content and the democratization of powerful creation
and editing techniques, establishing the provenance of media is critical to ensure transparency,
understanding, and ultimately, trust.

>We are witnessing extraordinary challenges to trust in media. As social platforms amplify
the reach and influence of certain content via ever more complex and opaque algorithms,
mis-attributed and mis-contextualized content spreads quickly. Whether inadvertent
misinformation or deliberate deception via disinformation, collectively inauthentic content is
on the rise.

Currently, creators who wish to include metadata about their work (for example authorship)
cannot do so in a secure, tamper-evident and standard way across platforms. Without this
attribution information, publishers and consumers lack critical context for determining the
authenticity of media. 

>Provenance empowers content creators and editors, regardless of their
geographic location or degree of access to technology, to disclose information about who
created or changed an asset, what was changed and how it was changed. 
Content with provenance exposes indicators of authenticity so
that consumers can have awareness of who has altered content and what exactly has been
changed. This ability to provide provenance for creators, publishers and consumers is
essential to engender trust online.

**Comment by lrosenthol** [comment]
changed exposes -> provides in the proposal to address your recommendation!

**Comment by pprindeville** [comment]
I also thought "engenders" was the wrong word, and "facilitates" was better.

"standard way" or "standards-based way" or "standardized way"?

**Comment by JacoboWitness** [comment]
This looks great!

Two quick comments:

1. It seems like the first phrase is missing a word? The velocity of digital content ... transformation? evolution? 

2. There is a lot of emphasis on establishing the origin of content but less so on the edits it may have gone through. Although we are using provenance to include both source and history, the more popular connotation points to origin. In the first paragraph we could clarify that as it is done in the website: "source and history (or provenance) of media content".

**Comment by yogeshbdeshpande** [comment]
@lrosenthol Is there anything outstanding, I believe now this needs to be closed ?
