### ISSUE TITLE
Missing relevance of Redaction!

### ISSUE THREAD

**Issue by yogeshbdeshpande** [c2pa-org/public-draft#23]
**Describe the issue**
Section 5.7 describes the mechanism of Redaction of Assertion.
What is clearly missing from the specification is the relevance as to why Redaction might be necessary?

Why provenance and corresponding metadata claims are ingredients in a manifest that you want to redact ?

**Comment by lrosenthol** [comment]
TWG Agrees to address for next public draft

**Comment by lrosenthol** [comment]
The Explainer and the Guidance document both include information about Redaction.
