### ISSUE TITLE
Duplicate JUMBF

### ISSUE THREAD

**Issue by hackerfactor** [c2pa-org/public-draft#31]
The draft spec does not define error handling if there are two separate JUMBF blocks defined that both contain provenance information.

**Comment by lrosenthol** [comment]
Now that we no longer mandate the XMP pointer to the active manifest(#30) , you are correct that we need to address this specific case.   Thanks!

**Comment by johnsim** [comment]
great catch, @hackerfactor!

**Comment by lrosenthol** [comment]
The solution for this has been included into the upcoming 1.0 specification.   Thanks again for this catch!

**Comment by lrosenthol** [comment]
Published.
