### ISSUE TITLE
Mandatory APP segment

### ISSUE THREAD

**Issue by hackerfactor** [c2pa-org/public-draft#32]
The APP numbers are supposed to be flexible.
EXIF typically uses APP1.  However, I've seen examples that put it in other APP segments.
"Adobe_CM" should use APP13, but I've seen examples that put it in APP0.

The JPEG parser is supposed to use the APP label to determine the type of data. The APP number is used to combine data when there it too much data for a single APP segment.
(The exception being Samsung preview images, that increment segments from APP2 to APP3 to APP4, etc. Why? Who knows. I guess they didn't read the JPEG standard.)

By convention, we typically see EXIF in APP1, XMP in APP1, ICC_PROFILE in APP2, etc. But this is not required.

Section 10.2.1 states that the JUMBF should be in APP11. What if it is not found in APP11? E.g., what if it is in some other APP segment? This is not defined in the draft.

**Comment by lrosenthol** [comment]
The presence of JUMBF in APP11 is standardized in JPEG-XT (ISO/IEC 18477-3) as well as in the JUMBF spec itself, Annex D.

**Comment by lrosenthol** [comment]
Closing as this is not an issue, but the 1.0 version of the specification does have an explicit reference to the JPEG-XT spec and APP11 marker usage to avoid future confusion.
