### ISSUE TITLE
Navigation doesn't work on new Specs page

### ISSUE THREAD

**Issue by andrewjenks** [c2pa-org/public-draft#36]
1. Go to Specification page in c2pa.org.
2. Click on any of the doc buttons.
3. Go back in the browser.

Result: Blank page with navigation
Expected: Return to Specification page UI

**Comment by lrosenthol** [comment]
Yes, this is a known issue with the use of `iframes` on that page.  It will be resolved with the improved docs model that will exist for 1.0.

**Comment by bquinn** [comment]
I agree, it's quite a bad experience. Also the URL bar doesn't update when
you click on one of the documents which is quite confusing.

The layout looks fairly simple, is there a reason why it needs to use
iframes?

(Congrats on getting 0.8 out the door, by the way!)

**Comment by lrosenthol** [comment]
>The layout looks fairly simple, is there a reason why it needs to use iframes?
>
Saved having to add the navigation bar each source file individually.

If all goes well, I can get the new system working sooner and just deploy that instead.

**Comment by lrosenthol** [comment]
The new 1.0 publishing system addresses this...closing
