### ISSUE TITLE
Remove 'padding' and add in hash lengths

### ISSUE THREAD

**Issue by hackerfactor** [c2pa-org/public-draft#38]
Section 9.4.5:

When generating hashes, the current specifications provide the hash and optional padding.
For example:
  [cbor]
  [hash field='Item 1: name' value='jumbf manifest'/]
  [hash field='Item 2: alg' value='sha256'/]
  [hash field='Item 3: hash' value='0x626e581febcad8fc3b44e65f565ab8d7d1f64e97883fe9be2c106b085c3d96f6' length='32'/]
  [hash field='Item 4: pad' value='0x20202020202020' length='7'/]
  [/cbor]

While some hashes, like sha256, are fixed-length, other hashes (e.g., cert-based signatures) may be variable length.
The 'pad' field is supposed to provide room for a variable-length hash.

The problem is that the pad is both optional and variable.

I propose changing the optional 'pad' field to an optional 'hash-length' field.
  [cbor]
  [hash field='Item 1: name' value='jumbf manifest'/]
  [hash field='Item 2: alg' value='sha256'/]
  [hash field='Item 3: hash' value='0x626e581febcad8fc3b44e65f565ab8d7d1f64e97883fe9be2c106b085c3d96f6' length='32'/]
  [hash field='Item 4: hash-length' value='32'/]
  [/cbor]

If the hash-length is not defined, then the hash's value is assumed to consume the entire length of the hash item. (In this example, without item 4, the hash is assumed to be the full 32 bytes specified by item 3.)

For a variable-length hash, the hash item (item 3) can have a much longer length. In effect, the hash field includes all of it's padding. All unused padding bytes must be at the end of the hash's allocated space (end of item 3) and all padding bytes must have the value of 0x00 or 0x20. (No uninitialized memory. For binary, use 0x00. For text, use 0x20 [space].)  The added "hash-length" item (item 4) identifies the number of used bytes in the variable-length hash (item 3).

This change:
1. Permits removing optional and unverified pad space. (Document 9.4.5 says that the pad space is not validated.)
2. Supports variable-length hashes with verifiable padding. (Any padding is identified and must be initialized correctly.)
3. Does not limit the padding to 16 bytes (as recommended in section 9.4.2). In particular, some hash algorithms may require more variability than 16 bytes. (E.g., PGP signatures.)

**Comment by paulengland** [comment]
Hi @hackerfactor

We introduced padding in in some structures/maps for a reason unrelated to the size of the hash field.  Specifically, the size of some fields are not known when you start to create the manifest.  We thought it made things a bit easier for claim creators if they could “go back and fill in” when more of the manifest is known.  The padding allows a claim creator to leave enough space for the variable length fields.  (There are other ways of creating the manifest and embedding it in an asset, but the padding field allows single-pass and memory-efficient algorithms.)

So the padding size recommended in 9.4.2 is unrelated to hashing: it is simply that the data-hash-map that contains the padding also contains two or more CBOR-encoded ints, and depending on the value of the encoded integers, the encoded length of these fields may be 1, 2, 3, 4… bytes.  The recommended length is just a hint to reduce the likelihood that the claim creator doesn’t leave enough space and has to start again.   Of course, if a future version of the spec included variable/unpredictable length hashes (and the hashes aren’t know when the map is first instantiated) then the claim creator could leave a bit more space for that purpose as well.

Onto your main points about hashing:

The CBOR encoding of byte arrays (as well as JSON, and every other potential future encoding that we have considered) explicitly includes the length.  So while it would be an error in the v1 of the spec if the length of the hash field did not match the length implicit in the algorithm (“sha256”, “sha384”…) I think that the spec would accommodated future hashes of variable length.

If the hash itself contains one or more variable length fields, the sub-structure of the hash cannot be expressed with a single implicit length field.  If this situation arises in the future, I think I would address this by creating a map for the parts of the digest, and serializing this to the bstr encoded in “hash.”  

Please let us know if we missed some subtlety, or if this does not solve the problems you are seeing. 

Paul

**Comment by hackerfactor** [comment]
Hi @paulengland,

Based on your reply, I think I'm linking together a couple of issues.

1. Padding must be initialized. If it's binary, then use 0x00. If it's string, then use a space (0x20). Uninitialized or incorrectly initialized padding must invalidate the adjacent hash, even if the hash's exclusion list doesn't include the padding.

The reason: Every sha-based and cert-based collision attack today alters unused space (padding) in order to force a collision. (MD5 had content collesions, but so far today, sha256 and larger only have padding collisions.) By forcing the padding to be initialized, it mitigates the risk from unauthenticated padding being used for a hash collision.

2. The amout of padding must be must be smaller than the hash size.

sha256 requires 32 bytes (binary). The padding can be 0 to 31 bytes.
sha384 requires 48 bytes (binary). The padding can be 0 to 47 bytes.
If there is any more padding, then it can (in theory) be used to force a collision.
NOTE: Technically, these hash algorithms read data in blocks. The amount of padding must not introduce another block. In reality, it can be difficult to count the number of input bytes prior to generating the hash. Limiting the padding to the hash output size is good enough.

The specs simply say no more than 32 bytes. At 32 bytes, it can theoretically force a collision with sha256, and may not be large enough for sha384.

By restricting the padding size, we can introduce one other type of validation: padding size! If there are 40 bytes padding, then the hash had better use sha384 or larger.  If I see 40 bytes padding with sha256, then I know someone changed the hash and hash algorithm.

3. The padding must be limited to the local scope. Not the global or inherited scope.
In my example, there's a cbor with a hash and pad. The pad is only to be used with that cbor object. If some other, adjacent object requires padding, then it must include it's own padding and not rely on an adjacent data structure to contain the padding.

This restriction serves two purposes: (1) mitigating hash collision attacks, and (2) keeping separate objects separate. There should not be a cross-over functional data dependency between adjacent or non-nested objects.

**Comment by lrosenthol** [comment]
A few comments @hackerfactor 

1a - All padding is defined to use 0x00 bytes and must be initialized/set to something.  However, I will give the spec a once over to make sure this is clearly spelled out in all cases.
1b - Since padding is inside of an assertion, which is hashed in its entirety as part of specifying it in the claim, there is no chance that it can be modified w/o detection.

2 - While I agree that is true that it will probably never be larger, there is no reason to prevent it.  I can't see how it could be used to force a collision.   And as noted in 1b, you can't change the hashing algorithm or result w/o detection.

3 - Completely agree.  I am happy to make that clearer in the spec if you'd like

**Comment by lrosenthol** [comment]
The solution for this has been included into the upcoming 1.0 specification.

**Comment by lrosenthol** [comment]
Published.
