### ISSUE TITLE
C2PA specifications are reference to private repo

### ISSUE THREAD

**Issue by mzeinstra** [c2pa-org/public-draft#43]
https://c2pa.org/ welcomes comments on the specifications and links to: https://github.com/c2pa-org/specifications/issues

however, that source is in a (probably) private repo and thus gives a 404.

I expected it to be In a public repo. Is this the repo that the page should refer to?

**Comment by lrosenthol** [comment]
@mzeinstra - that link is to a public repo with contains our repository for the specification itself.  Are you having issues accessing that repo?

We do have private repos as well, but I don't believe any are referenced from public documentation.

**Comment by mzeinstra** [comment]
@lrosenthol - Thanks for the reply. Are you sure that is set to public? See the screenshot of the 404 I see when I click on the link: https://github.com/c2pa-org/specifications/issues

<img width="1841" alt="Screenshot 2022-03-10 at 09 48 54" src="https://user-images.githubusercontent.com/5627431/157625205-9cb65c37-421f-4061-8c0b-b5ed0c91b0f9.png">

**Comment by kevinmkane** [comment]
I'm seeing that as well if I'm not logged in. "specifications" is still private and shouldn't be.

**Comment by lrosenthol** [comment]
Sorry - try now!

**Comment by mzeinstra** [comment]
Yep works now, thanks!
